import initScrollSuave from "./modules/scroll-suave.js";
import initAnimationScroll from "./modules/animacao-scroll.js";
import initAcordion from "./modules/acordion-list.js";
import initTabNav from "./modules/tabnav.js";
import initModal from "./modules/modal.js";
import initToolTip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdraw.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initFunctionamento from "./modules/funcionamento.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";

initScrollSuave();
initAnimationScroll();
initAcordion();
initTabNav();
initModal();
initToolTip();
initDropdownMenu();
initMenuMobile();
initFunctionamento();
initFetchAnimais();
initFetchAnimais();
